services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - ../:/workspace
    restart: unless-stopped
